-- ============================================
-- Oracle 初始化脚本
-- ============================================

-- 创建序列号段表
CREATE TABLE sequence_segment (
    id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_key VARCHAR2(64) NOT NULL UNIQUE,
    min_value NUMBER(20) DEFAULT 1 NOT NULL,
    max_value NUMBER(20) NOT NULL,
    current_max_value NUMBER(20) NOT NULL,
    step NUMBER(10) DEFAULT 1000 NOT NULL,
    version NUMBER(10) DEFAULT 0 NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 创建索引
CREATE INDEX idx_segment_biz_key ON sequence_segment(biz_key);
CREATE INDEX idx_segment_update_time ON sequence_segment(update_time);

-- 创建序列配置表
CREATE TABLE sequence_config (
    id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_key VARCHAR2(64) NOT NULL UNIQUE,
    sequence_type VARCHAR2(32) NOT NULL,
    step NUMBER(10) DEFAULT 1000 NOT NULL,
    date_format VARCHAR2(32),
    prefix VARCHAR2(32),
    suffix VARCHAR2(32),
    min_value NUMBER(20) DEFAULT 1 NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    description VARCHAR2(256),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 创建序列使用统计表
CREATE TABLE sequence_statistics (
    id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_key VARCHAR2(64) NOT NULL,
    sequence_type VARCHAR2(32) NOT NULL,
    current_value NUMBER(20) DEFAULT 0 NOT NULL,
    total_count NUMBER(20) DEFAULT 0 NOT NULL,
    stat_date DATE NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_statistics_biz_date ON sequence_statistics(biz_key, stat_date);
CREATE INDEX idx_statistics_date ON sequence_statistics(stat_date);

-- 创建触发器自动更新时间戳
CREATE OR REPLACE TRIGGER trg_segment_update_time
BEFORE UPDATE ON sequence_segment
FOR EACH ROW
BEGIN
    :NEW.update_time := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_config_update_time
BEFORE UPDATE ON sequence_config
FOR EACH ROW
BEGIN
    :NEW.update_time := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_statistics_update_time
BEFORE UPDATE ON sequence_statistics
FOR EACH ROW
BEGIN
    :NEW.update_time := CURRENT_TIMESTAMP;
END;
/

-- 插入测试数据
MERGE INTO sequence_segment s
USING (SELECT 'order_id' AS biz_key FROM DUAL UNION ALL
       SELECT 'user_id' FROM DUAL UNION ALL
       SELECT 'payment_id' FROM DUAL) src
ON (s.biz_key = src.biz_key)
WHEN MATCHED THEN
    UPDATE SET s.update_time = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (id, biz_key, min_value, max_value, current_max_value, step)
    VALUES (sequence_segment_seq.NEXTVAL, src.biz_key, 1, 1000, 1000, 1000);
